image: python:3-slim

before_script:
  - pip install ansible-lint
  - ansible-lint --version

stages:
  - ansible-lint
  - execute-test

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint .

execute-test:
  stage: execute-test
  script:
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local