image: registry.gitlab.com/gianet/moegui/devops/devops/ansible:2.9

stages:
  - ansible-lint
#  - execute-test

ansible-lint:
  stage: ansible-lint
  script:
    - ansible-lint .

# execute-test:
#   stage: execute-test
#   script:
#     - ansible-playbook -i tests/inventory tests/test.yml --connection=local
